export type DemoResourceGraphNode = {
  id: string;
  type: 'force-unit' | 'platform' | 'weapon' | 'sensor' | 'geo-zone' | 'mission';
  name: string;
  side?: 'red' | 'blue' | 'neutral';
  capabilities: string[];
  status: 'available' | 'unavailable' | 'reserved';
  metadata: Record<string, string | number | boolean | string[]>;
};

export type DemoResourceGraphRelationship = {
  id: string;
  type:
    | 'belongs_to'
    | 'can_command'
    | 'can_communicate'
    | 'can_detect'
    | 'can_strike'
    | 'can_support'
    | 'deployable_to'
    | 'suitable_for';
  from: string;
  to: string;
  label: string;
  metadata: Record<string, string | number | boolean>;
};

export const ONTOLOGY_ROOTS = ['ForceUnit', 'Platform', 'GeoZone', 'Mission'] as const;

export const demoForceUnits = [
  {
    id: 'force-source-101',
    unitName: '蓝军机动对抗分队',
    unitType: 'ground' as const,
    forceSide: 'blue' as const,
    commandRelation: 'force-source-102',
    standardSymbolCode: 'SFGPU-----------',
    maxSpeed: 80,
    maxRange: 500,
    sensorRange: 50,
    strikeRange: 30,
    dataSource: 'demo',
    confidence: 'high' as const,
  },
];

export const demoPlatforms = [
  {
    id: 'platform-source-207',
    platformName: '电子侦察平台-07',
    platformType: 'ship' as const,
    weaponSystems: [],
    sensorTypes: ['electronic'],
    propulsionType: 'diesel',
    sizeClass: 'medium' as const,
    maxSpeed: 30,
    maxRange: 2000,
    sensorRange: 100,
    strikeRange: 0,
    dataSource: 'demo',
    confidence: 'high' as const,
  },
];

export const demoGeoZones = [
  {
    id: 'geo-zone-tw-001',
    zoneName: '台湾北部空域',
    zoneType: 'operation-zone' as const,
    polygon: {
      type: 'Polygon',
      coordinates: [[[121.0, 25.1], [122.0, 25.1], [122.0, 26.0], [121.0, 26.0], [121.0, 25.1]]],
    },
    altitudeBand: { min: 0, max: 10000 },
    controlAuthority: 'blue',
    dataSource: 'demo',
  },
];

export const demoResourceGraphNodes: DemoResourceGraphNode[] = [
  {
    id: 'unit-blue-c2-001',
    type: 'force-unit',
    name: '蓝方联合指挥节点',
    side: 'blue',
    capabilities: ['command_link', 'communication_control'],
    status: 'available',
    metadata: {
      echelon: 'joint-command',
      homeRegion: '台湾东部海域',
      commandPostType: 'air-sea-joint',
      simultaneousLinks: 24,
      sourceEntityId: 'force-source-101',
    },
  },
  {
    id: 'unit-blue-ew-001',
    type: 'force-unit',
    name: '蓝方电子对抗分队',
    side: 'blue',
    capabilities: ['ew_support', 'communication_jamming', 'electronic_detection'],
    status: 'available',
    metadata: {
      echelon: 'tactical-ew-group',
      homeRegion: '台湾东部海域',
      deployReadinessMin: 25,
      supportedMissionTypes: ['侦察打击', '电磁压制'],
    },
  },
  {
    id: 'unit-blue-strike-001',
    type: 'force-unit',
    name: '蓝方远程打击分队',
    side: 'blue',
    capabilities: ['long_range_strike', 'anti_surface_strike', 'strike_coordination'],
    status: 'available',
    metadata: {
      echelon: 'strike-package',
      homeRegion: '西太平洋前出空域',
      salvoCapacity: 12,
      supportedMissionTypes: ['侦察打击', '联合火力打击'],
    },
  },
  {
    id: 'unit-blue-defense-001',
    type: 'force-unit',
    name: '蓝方区域防空分队',
    side: 'blue',
    capabilities: ['area_air_defense', 'early_warning', 'command_link'],
    status: 'reserved',
    metadata: {
      echelon: 'air-defense-group',
      homeRegion: '台湾北部空域',
      readinessState: 'mission-reserve',
      supportedMissionTypes: ['区域防空', '要域掩护'],
    },
  },
  {
    id: 'platform-blue-recon-001',
    type: 'platform',
    name: '电子侦察平台-07',
    side: 'blue',
    capabilities: ['air_recon', 'ew_support', 'electronic_detection'],
    status: 'available',
    metadata: {
      platformType: 'air-recon',
      maxRangeKm: 1800,
      sensorRangeKm: 350,
      defaultLongitude: 123.8,
      defaultLatitude: 24.6,
      defaultAltitude: 9000,
      enduranceHours: 8,
      sourceEntityId: 'platform-source-207',
      compatiblePayloads: ['sensor-blue-electronic-001', 'sensor-blue-optical-001'],
    },
  },
  {
    id: 'platform-blue-awacs-001',
    type: 'platform',
    name: '空中预警指挥平台-01',
    side: 'blue',
    capabilities: ['air_recon', 'early_warning', 'command_link', 'communication_relay'],
    status: 'available',
    metadata: {
      platformType: 'air-awacs',
      maxRangeKm: 2600,
      sensorRangeKm: 520,
      defaultLongitude: 123.1,
      defaultLatitude: 25.2,
      defaultAltitude: 9200,
      simultaneousTracks: 180,
    },
  },
  {
    id: 'platform-blue-uav-001',
    type: 'platform',
    name: '高空长航时无人侦察机-05',
    side: 'blue',
    capabilities: ['air_recon', 'electro_optical_recon', 'target_tracking'],
    status: 'available',
    metadata: {
      platformType: 'hae-uav',
      maxRangeKm: 3200,
      sensorRangeKm: 220,
      defaultLongitude: 122.9,
      defaultLatitude: 24.2,
      defaultAltitude: 13000,
      enduranceHours: 22,
    },
  },
  {
    id: 'platform-blue-jammer-001',
    type: 'platform',
    name: '电子压制平台-03',
    side: 'blue',
    capabilities: ['ew_support', 'communication_jamming'],
    status: 'available',
    metadata: {
      platformType: 'air-jammer',
      maxRangeKm: 1500,
      sensorRangeKm: 180,
      defaultLongitude: 124.2,
      defaultLatitude: 24.9,
      defaultAltitude: 8500,
      jammerBands: ['vhf', 'uhf', 'data-link'],
      effectiveRadiusKm: 180,
    },
  },
  {
    id: 'platform-blue-relay-001',
    type: 'platform',
    name: '战术通信中继平台-02',
    side: 'blue',
    capabilities: ['communication_relay', 'communication_control', 'command_link'],
    status: 'available',
    metadata: {
      platformType: 'air-relay',
      maxRangeKm: 1600,
      relayRadiusKm: 260,
      defaultLongitude: 123.6,
      defaultLatitude: 25.0,
      defaultAltitude: 7800,
      bandwidthMbps: 80,
    },
  },
  {
    id: 'platform-blue-strike-001',
    type: 'platform',
    name: '远程打击编队-11',
    side: 'blue',
    capabilities: ['long_range_strike', 'anti_surface_strike'],
    status: 'available',
    metadata: {
      platformType: 'air-multirole',
      maxRangeKm: 2200,
      strikeRangeKm: 450,
      defaultLongitude: 123.5,
      defaultLatitude: 24.1,
      defaultAltitude: 10000,
      weaponsCapacity: 8,
      requiredSupport: ['targeting', 'electronic-suppression'],
    },
  },
  {
    id: 'platform-blue-ship-001',
    type: 'platform',
    name: '海上综合支援舰-21',
    side: 'blue',
    capabilities: ['maritime_support', 'communication_relay', 'area_air_defense'],
    status: 'available',
    metadata: {
      platformType: 'surface-combat-support',
      maxRangeKm: 4800,
      sensorRangeKm: 260,
      defaultLongitude: 123.3,
      defaultLatitude: 23.7,
      defaultAltitude: 0,
      supportCapacity: 'air-sea-package',
    },
  },
  {
    id: 'platform-blue-tanker-001',
    type: 'platform',
    name: '空中加油保障平台-04',
    side: 'blue',
    capabilities: ['air_refuel', 'long_endurance_support', 'support'],
    status: 'available',
    metadata: {
      platformType: 'air-tanker',
      maxRangeKm: 3800,
      supportRadiusKm: 700,
      defaultLongitude: 122.8,
      defaultLatitude: 23.8,
      defaultAltitude: 7600,
      fuelOffloadTons: 58,
    },
  },
  {
    id: 'platform-blue-sam-001',
    type: 'platform',
    name: '机动防空火力单元-06',
    side: 'blue',
    capabilities: ['area_air_defense', 'point_defense', 'early_warning'],
    status: 'reserved',
    metadata: {
      platformType: 'ground-sam',
      maxRangeKm: 600,
      strikeRangeKm: 120,
      defaultLongitude: 121.9,
      defaultLatitude: 25.3,
      defaultAltitude: 120,
      readinessState: 'reserve',
    },
  },
  {
    id: 'sensor-blue-electronic-001',
    type: 'sensor',
    name: '宽域电子侦察载荷',
    side: 'blue',
    capabilities: ['electronic_detection', 'signal_intercept'],
    status: 'available',
    metadata: {
      sensorType: 'ew',
      rangeKm: 350,
      frequencyBands: ['vhf', 'uhf', 'l-band', 's-band'],
      precision: 'medium-high',
    },
  },
  {
    id: 'sensor-blue-aesa-001',
    type: 'sensor',
    name: '有源相控阵预警雷达',
    side: 'blue',
    capabilities: ['early_warning', 'air_recon', 'target_tracking'],
    status: 'available',
    metadata: {
      sensorType: 'aesa-radar',
      rangeKm: 520,
      trackCapacity: 180,
      hostPlatform: 'platform-blue-awacs-001',
    },
  },
  {
    id: 'sensor-blue-optical-001',
    type: 'sensor',
    name: '远距光电侦察载荷',
    side: 'blue',
    capabilities: ['electro_optical_recon', 'target_identification'],
    status: 'available',
    metadata: {
      sensorType: 'eo-ir',
      rangeKm: 220,
      hostPlatform: 'platform-blue-uav-001',
      nightCapability: true,
    },
  },
  {
    id: 'sensor-blue-passive-001',
    type: 'sensor',
    name: '被动定位接收阵列',
    side: 'blue',
    capabilities: ['passive_detection', 'signal_intercept', 'electronic_detection'],
    status: 'available',
    metadata: {
      sensorType: 'passive-location',
      rangeKm: 280,
      triangulation: true,
      supports: 'platform-blue-jammer-001',
    },
  },
  {
    id: 'weapon-blue-stand-off-001',
    type: 'weapon',
    name: '防区外精确打击弹药',
    side: 'blue',
    capabilities: ['long_range_strike'],
    status: 'available',
    metadata: {
      weaponType: 'stand-off',
      rangeKm: 450,
      compatiblePlatform: 'platform-blue-strike-001',
      targetTypes: ['surface', 'fixed-site'],
    },
  },
  {
    id: 'weapon-blue-anti-radiation-001',
    type: 'weapon',
    name: '反辐射压制弹药',
    side: 'blue',
    capabilities: ['anti_radiation_strike', 'sead'],
    status: 'available',
    metadata: {
      weaponType: 'anti-radiation',
      rangeKm: 280,
      compatiblePlatform: 'platform-blue-strike-001',
      targetTypes: ['radar', 'emitter'],
    },
  },
  {
    id: 'weapon-blue-cruise-001',
    type: 'weapon',
    name: '远程巡航打击弹药',
    side: 'blue',
    capabilities: ['long_range_strike', 'precision_strike'],
    status: 'reserved',
    metadata: {
      weaponType: 'cruise',
      rangeKm: 900,
      compatiblePlatform: 'platform-blue-ship-001',
      targetTypes: ['fixed-site', 'command-post'],
    },
  },
  {
    id: 'weapon-blue-sam-001',
    type: 'weapon',
    name: '区域防空拦截弹',
    side: 'blue',
    capabilities: ['area_air_defense', 'point_defense'],
    status: 'reserved',
    metadata: {
      weaponType: 'sam-interceptor',
      rangeKm: 120,
      compatiblePlatform: 'platform-blue-sam-001',
      targetTypes: ['aircraft', 'missile'],
    },
  },
  {
    id: 'geo-zone-east-taiwan-sea',
    type: 'geo-zone',
    name: '台湾东部海域',
    side: 'neutral',
    capabilities: ['air_operation_area', 'maritime_operation_area'],
    status: 'available',
    metadata: {
      lonMin: 122,
      lonMax: 126,
      latMin: 22,
      latMax: 26,
      riskLevel: 'medium',
      dominantDomain: 'air-maritime',
    },
  },
  {
    id: 'geo-zone-north-taiwan-air',
    type: 'geo-zone',
    name: '台湾北部空域',
    side: 'neutral',
    capabilities: ['air_operation_area', 'early_warning_area'],
    status: 'available',
    metadata: {
      lonMin: 120.6,
      lonMax: 123.2,
      latMin: 24.5,
      latMax: 26.3,
      riskLevel: 'high',
      dominantDomain: 'air',
    },
  },
  {
    id: 'geo-zone-western-pacific',
    type: 'geo-zone',
    name: '西太平洋前出空域',
    side: 'neutral',
    capabilities: ['air_operation_area', 'support_area'],
    status: 'available',
    metadata: {
      lonMin: 123.5,
      lonMax: 128.5,
      latMin: 21.8,
      latMax: 26.8,
      riskLevel: 'low',
      dominantDomain: 'air-support',
    },
  },
  {
    id: 'geo-zone-taiwan-strait',
    type: 'geo-zone',
    name: '台湾海峡通道',
    side: 'neutral',
    capabilities: ['maritime_operation_area', 'strike_corridor'],
    status: 'available',
    metadata: {
      lonMin: 118.8,
      lonMax: 121.4,
      latMin: 23.0,
      latMax: 25.8,
      riskLevel: 'high',
      dominantDomain: 'maritime',
    },
  },
  {
    id: 'mission-recon-strike',
    type: 'mission',
    name: '侦察打击任务',
    side: 'neutral',
    capabilities: ['air_recon', 'ew_support', 'long_range_strike', 'command_link'],
    status: 'available',
    metadata: {
      missionType: '侦察打击',
      requiredChains: ['command', 'communication', 'detection', 'strike', 'support'],
      priority: 'high',
    },
  },
  {
    id: 'mission-ew-suppression',
    type: 'mission',
    name: '电磁压制任务',
    side: 'neutral',
    capabilities: ['ew_support', 'communication_jamming', 'electronic_detection', 'sead'],
    status: 'available',
    metadata: {
      missionType: '电磁压制',
      requiredChains: ['command', 'detection', 'support'],
      priority: 'medium-high',
    },
  },
  {
    id: 'mission-area-defense',
    type: 'mission',
    name: '区域防空任务',
    side: 'neutral',
    capabilities: ['area_air_defense', 'early_warning', 'command_link'],
    status: 'available',
    metadata: {
      missionType: '区域防空',
      requiredChains: ['command', 'detection', 'support'],
      priority: 'medium',
    },
  },
];

export const demoResourceGraphRelationships: DemoResourceGraphRelationship[] = [
  {
    id: 'rel-blue-c2-command-ew-unit',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'unit-blue-ew-001',
    label: '联合指挥节点指挥电子对抗分队',
    metadata: { latencyMs: 70, reliability: 0.94 },
  },
  {
    id: 'rel-blue-c2-command-strike-unit',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'unit-blue-strike-001',
    label: '联合指挥节点指挥远程打击分队',
    metadata: { latencyMs: 95, reliability: 0.92 },
  },
  {
    id: 'rel-blue-c2-command-defense-unit',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'unit-blue-defense-001',
    label: '联合指挥节点指挥区域防空分队',
    metadata: { latencyMs: 85, reliability: 0.9 },
  },
  {
    id: 'rel-blue-c2-command-recon',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'platform-blue-recon-001',
    label: '指挥电子侦察平台',
    metadata: { latencyMs: 80, reliability: 0.95 },
  },
  {
    id: 'rel-blue-c2-command-jammer',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'platform-blue-jammer-001',
    label: '指挥电子压制平台',
    metadata: { latencyMs: 90, reliability: 0.93 },
  },
  {
    id: 'rel-blue-c2-command-strike',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'platform-blue-strike-001',
    label: '指挥远程打击编队',
    metadata: { latencyMs: 120, reliability: 0.9 },
  },
  {
    id: 'rel-blue-c2-command-awacs',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'platform-blue-awacs-001',
    label: '联合指挥节点指挥空中预警平台',
    metadata: { latencyMs: 75, reliability: 0.96 },
  },
  {
    id: 'rel-blue-c2-command-relay',
    type: 'can_command',
    from: 'unit-blue-c2-001',
    to: 'platform-blue-relay-001',
    label: '联合指挥节点指挥通信中继平台',
    metadata: { latencyMs: 65, reliability: 0.97 },
  },
  {
    id: 'rel-blue-ew-unit-controls-jammer',
    type: 'can_command',
    from: 'unit-blue-ew-001',
    to: 'platform-blue-jammer-001',
    label: '电子对抗分队控制电子压制平台',
    metadata: { latencyMs: 60, reliability: 0.95 },
  },
  {
    id: 'rel-blue-strike-unit-controls-strike',
    type: 'can_command',
    from: 'unit-blue-strike-001',
    to: 'platform-blue-strike-001',
    label: '远程打击分队控制远程打击编队',
    metadata: { latencyMs: 85, reliability: 0.91 },
  },
  {
    id: 'rel-blue-defense-unit-controls-sam',
    type: 'can_command',
    from: 'unit-blue-defense-001',
    to: 'platform-blue-sam-001',
    label: '区域防空分队控制机动防空火力单元',
    metadata: { latencyMs: 55, reliability: 0.92 },
  },
  {
    id: 'rel-recon-carries-sensor',
    type: 'belongs_to',
    from: 'sensor-blue-electronic-001',
    to: 'platform-blue-recon-001',
    label: '侦察载荷挂载于电子侦察平台',
    metadata: { fit: 'primary-payload' },
  },
  {
    id: 'rel-awacs-carries-aesa',
    type: 'belongs_to',
    from: 'sensor-blue-aesa-001',
    to: 'platform-blue-awacs-001',
    label: '有源相控阵雷达挂载于空中预警平台',
    metadata: { fit: 'integrated-sensor' },
  },
  {
    id: 'rel-uav-carries-optical',
    type: 'belongs_to',
    from: 'sensor-blue-optical-001',
    to: 'platform-blue-uav-001',
    label: '远距光电载荷挂载于无人侦察机',
    metadata: { fit: 'primary-payload' },
  },
  {
    id: 'rel-jammer-uses-passive-array',
    type: 'belongs_to',
    from: 'sensor-blue-passive-001',
    to: 'platform-blue-jammer-001',
    label: '被动定位阵列支撑电子压制平台',
    metadata: { fit: 'support-sensor' },
  },
  {
    id: 'rel-strike-carries-weapon',
    type: 'belongs_to',
    from: 'weapon-blue-stand-off-001',
    to: 'platform-blue-strike-001',
    label: '防区外弹药挂载于远程打击编队',
    metadata: { fit: 'primary-weapon' },
  },
  {
    id: 'rel-strike-carries-anti-radiation',
    type: 'belongs_to',
    from: 'weapon-blue-anti-radiation-001',
    to: 'platform-blue-strike-001',
    label: '反辐射弹药挂载于远程打击编队',
    metadata: { fit: 'sead-weapon' },
  },
  {
    id: 'rel-ship-carries-cruise',
    type: 'belongs_to',
    from: 'weapon-blue-cruise-001',
    to: 'platform-blue-ship-001',
    label: '远程巡航弹药由海上支援舰携行',
    metadata: { fit: 'maritime-strike-weapon' },
  },
  {
    id: 'rel-sam-carries-interceptor',
    type: 'belongs_to',
    from: 'weapon-blue-sam-001',
    to: 'platform-blue-sam-001',
    label: '区域防空拦截弹配属机动防空单元',
    metadata: { fit: 'air-defense-weapon' },
  },
  {
    id: 'rel-recon-detects-zone',
    type: 'can_detect',
    from: 'platform-blue-recon-001',
    to: 'geo-zone-east-taiwan-sea',
    label: '电子侦察平台覆盖台湾东部海域',
    metadata: { rangeKm: 350 },
  },
  {
    id: 'rel-awacs-detects-north-air',
    type: 'can_detect',
    from: 'platform-blue-awacs-001',
    to: 'geo-zone-north-taiwan-air',
    label: '空中预警平台覆盖台湾北部空域',
    metadata: { rangeKm: 520, trackCapacity: 180 },
  },
  {
    id: 'rel-uav-detects-strait',
    type: 'can_detect',
    from: 'platform-blue-uav-001',
    to: 'geo-zone-taiwan-strait',
    label: '无人侦察机持续监视台湾海峡通道',
    metadata: { rangeKm: 220, enduranceHours: 22 },
  },
  {
    id: 'rel-passive-detects-east-sea',
    type: 'can_detect',
    from: 'sensor-blue-passive-001',
    to: 'geo-zone-east-taiwan-sea',
    label: '被动定位阵列监听台湾东部海域电磁信号',
    metadata: { rangeKm: 280, passive: true },
  },
  {
    id: 'rel-sam-detects-north-air',
    type: 'can_detect',
    from: 'platform-blue-sam-001',
    to: 'geo-zone-north-taiwan-air',
    label: '机动防空单元监视台湾北部空域',
    metadata: { rangeKm: 120 },
  },
  {
    id: 'rel-strike-covers-zone',
    type: 'can_strike',
    from: 'platform-blue-strike-001',
    to: 'geo-zone-east-taiwan-sea',
    label: '远程打击编队覆盖台湾东部海域',
    metadata: { rangeKm: 450 },
  },
  {
    id: 'rel-anti-radiation-covers-strait',
    type: 'can_strike',
    from: 'weapon-blue-anti-radiation-001',
    to: 'geo-zone-taiwan-strait',
    label: '反辐射弹药可压制台湾海峡通道辐射源',
    metadata: { rangeKm: 280, targetType: 'emitter' },
  },
  {
    id: 'rel-cruise-covers-strait',
    type: 'can_strike',
    from: 'weapon-blue-cruise-001',
    to: 'geo-zone-taiwan-strait',
    label: '巡航弹药覆盖台湾海峡通道固定目标',
    metadata: { rangeKm: 900, targetType: 'fixed-site' },
  },
  {
    id: 'rel-sam-defends-north-air',
    type: 'can_strike',
    from: 'weapon-blue-sam-001',
    to: 'geo-zone-north-taiwan-air',
    label: '区域防空拦截弹覆盖台湾北部空域',
    metadata: { rangeKm: 120, targetType: 'air' },
  },
  {
    id: 'rel-recon-communicates-jammer',
    type: 'can_communicate',
    from: 'platform-blue-recon-001',
    to: 'platform-blue-jammer-001',
    label: '侦察平台向压制平台共享目标信号',
    metadata: { bandwidthMbps: 20 },
  },
  {
    id: 'rel-awacs-communicates-recon',
    type: 'can_communicate',
    from: 'platform-blue-awacs-001',
    to: 'platform-blue-recon-001',
    label: '空中预警平台向电子侦察平台下发空情线索',
    metadata: { bandwidthMbps: 40, latencyMs: 60 },
  },
  {
    id: 'rel-awacs-communicates-strike',
    type: 'can_communicate',
    from: 'platform-blue-awacs-001',
    to: 'platform-blue-strike-001',
    label: '空中预警平台向打击编队共享目标批次',
    metadata: { bandwidthMbps: 50, latencyMs: 70 },
  },
  {
    id: 'rel-relay-links-c2-jammer',
    type: 'can_communicate',
    from: 'platform-blue-relay-001',
    to: 'platform-blue-jammer-001',
    label: '通信中继平台保障指挥节点与电子压制平台链路',
    metadata: { bandwidthMbps: 80, latencyMs: 45 },
  },
  {
    id: 'rel-relay-links-strike',
    type: 'can_communicate',
    from: 'platform-blue-relay-001',
    to: 'platform-blue-strike-001',
    label: '通信中继平台保障打击编队数据链',
    metadata: { bandwidthMbps: 70, latencyMs: 55 },
  },
  {
    id: 'rel-ship-communicates-relay',
    type: 'can_communicate',
    from: 'platform-blue-ship-001',
    to: 'platform-blue-relay-001',
    label: '海上支援舰为通信中继平台提供海基链路备份',
    metadata: { bandwidthMbps: 60, backup: true },
  },
  {
    id: 'rel-jammer-supports-strike',
    type: 'can_support',
    from: 'platform-blue-jammer-001',
    to: 'platform-blue-strike-001',
    label: '电子压制平台支援远程打击编队',
    metadata: { supportType: 'electronic-suppression' },
  },
  {
    id: 'rel-awacs-supports-strike',
    type: 'can_support',
    from: 'platform-blue-awacs-001',
    to: 'platform-blue-strike-001',
    label: '空中预警平台支援远程打击编队目标分配',
    metadata: { supportType: 'target-cueing' },
  },
  {
    id: 'rel-uav-supports-strike',
    type: 'can_support',
    from: 'platform-blue-uav-001',
    to: 'platform-blue-strike-001',
    label: '无人侦察机为远程打击编队提供目标识别',
    metadata: { supportType: 'target-identification' },
  },
  {
    id: 'rel-tanker-supports-recon',
    type: 'can_support',
    from: 'platform-blue-tanker-001',
    to: 'platform-blue-recon-001',
    label: '空中加油平台延长电子侦察平台留空时间',
    metadata: { supportType: 'air-refuel', enduranceGainHours: 4 },
  },
  {
    id: 'rel-tanker-supports-strike',
    type: 'can_support',
    from: 'platform-blue-tanker-001',
    to: 'platform-blue-strike-001',
    label: '空中加油平台保障远程打击编队前出半径',
    metadata: { supportType: 'air-refuel', radiusGainKm: 450 },
  },
  {
    id: 'rel-ship-supports-defense',
    type: 'can_support',
    from: 'platform-blue-ship-001',
    to: 'platform-blue-sam-001',
    label: '海上支援舰支援机动防空火力单元态势共享',
    metadata: { supportType: 'maritime-cueing' },
  },
  {
    id: 'rel-mission-suitable-recon',
    type: 'suitable_for',
    from: 'platform-blue-recon-001',
    to: 'mission-recon-strike',
    label: '电子侦察平台适合侦察打击任务',
    metadata: { score: 0.92, reason: '满足侦察与电子支援能力' },
  },
  {
    id: 'rel-mission-suitable-strike',
    type: 'suitable_for',
    from: 'platform-blue-strike-001',
    to: 'mission-recon-strike',
    label: '远程打击编队适合侦察打击任务',
    metadata: { score: 0.9, reason: '满足远程打击能力' },
  },
  {
    id: 'rel-mission-suitable-awacs',
    type: 'suitable_for',
    from: 'platform-blue-awacs-001',
    to: 'mission-recon-strike',
    label: '空中预警平台适合侦察打击任务',
    metadata: { score: 0.88, reason: '提供预警、指挥和目标分配' },
  },
  {
    id: 'rel-mission-suitable-jammer-ew',
    type: 'suitable_for',
    from: 'platform-blue-jammer-001',
    to: 'mission-ew-suppression',
    label: '电子压制平台适合电磁压制任务',
    metadata: { score: 0.94, reason: '具备通信干扰与电磁压制能力' },
  },
  {
    id: 'rel-mission-suitable-passive-ew',
    type: 'suitable_for',
    from: 'sensor-blue-passive-001',
    to: 'mission-ew-suppression',
    label: '被动定位阵列适合电磁压制任务',
    metadata: { score: 0.84, reason: '支撑辐射源定位和信号截获' },
  },
  {
    id: 'rel-mission-suitable-sam-defense',
    type: 'suitable_for',
    from: 'platform-blue-sam-001',
    to: 'mission-area-defense',
    label: '机动防空火力单元适合区域防空任务',
    metadata: { score: 0.89, reason: '具备区域防空和点防御能力' },
  },
  {
    id: 'rel-mission-suitable-defense-unit',
    type: 'suitable_for',
    from: 'unit-blue-defense-001',
    to: 'mission-area-defense',
    label: '区域防空分队适合区域防空任务',
    metadata: { score: 0.91, reason: '具备防空指挥和预警能力' },
  },
  {
    id: 'rel-platform-deployable-east-taiwan',
    type: 'deployable_to',
    from: 'platform-blue-recon-001',
    to: 'geo-zone-east-taiwan-sea',
    label: '电子侦察平台可部署至台湾东部海域',
    metadata: { deployTimeMin: 35, risk: 'medium' },
  },
  {
    id: 'rel-awacs-deployable-north-air',
    type: 'deployable_to',
    from: 'platform-blue-awacs-001',
    to: 'geo-zone-north-taiwan-air',
    label: '空中预警平台可部署至台湾北部空域',
    metadata: { deployTimeMin: 40, risk: 'high' },
  },
  {
    id: 'rel-uav-deployable-strait',
    type: 'deployable_to',
    from: 'platform-blue-uav-001',
    to: 'geo-zone-taiwan-strait',
    label: '无人侦察机可部署至台湾海峡通道',
    metadata: { deployTimeMin: 30, risk: 'high' },
  },
  {
    id: 'rel-jammer-deployable-east-sea',
    type: 'deployable_to',
    from: 'platform-blue-jammer-001',
    to: 'geo-zone-east-taiwan-sea',
    label: '电子压制平台可部署至台湾东部海域',
    metadata: { deployTimeMin: 38, risk: 'medium' },
  },
  {
    id: 'rel-strike-deployable-west-pacific',
    type: 'deployable_to',
    from: 'platform-blue-strike-001',
    to: 'geo-zone-western-pacific',
    label: '远程打击编队可部署至西太平洋前出空域',
    metadata: { deployTimeMin: 45, risk: 'low' },
  },
  {
    id: 'rel-tanker-deployable-west-pacific',
    type: 'deployable_to',
    from: 'platform-blue-tanker-001',
    to: 'geo-zone-western-pacific',
    label: '空中加油保障平台可部署至西太平洋前出空域',
    metadata: { deployTimeMin: 50, risk: 'low' },
  },
  {
    id: 'rel-ship-deployable-east-sea',
    type: 'deployable_to',
    from: 'platform-blue-ship-001',
    to: 'geo-zone-east-taiwan-sea',
    label: '海上综合支援舰可部署至台湾东部海域',
    metadata: { deployTimeMin: 180, risk: 'medium' },
  },
  {
    id: 'rel-sam-deployable-north-air',
    type: 'deployable_to',
    from: 'platform-blue-sam-001',
    to: 'geo-zone-north-taiwan-air',
    label: '机动防空火力单元可部署至台湾北部空域',
    metadata: { deployTimeMin: 95, risk: 'high' },
  },
];
