import type { WeaponSpec } from '../types/tactical-scenario';

export const WEAPON_DATABASE: Record<string, WeaponSpec> = {
  'aim-9x': {
    id: 'aim-9x',
    type: 'aam-short',
    name: 'AIM-9X 响尾蛇',
    guidance: 'infrared',
    maxRange: 35_000,
    minRange: 500,
    cruiseSpeedMps: 820,
    terminalSpeedMps: 950,
    acceleration: 40,
    turnRate: 60,
    warheadWeight: 9.4,
    killRadius: 10,
    launchDelay: 0.5,
    lockTime: 2,
  },
  'aim-120d': {
    id: 'aim-120d',
    type: 'aam-medium',
    name: 'AIM-120D AMRAAM',
    guidance: 'active-radar',
    maxRange: 160_000,
    minRange: 1_000,
    cruiseSpeedMps: 1_100,
    terminalSpeedMps: 1_350,
    acceleration: 30,
    turnRate: 40,
    warheadWeight: 18,
    killRadius: 15,
    launchDelay: 1,
    lockTime: 5,
  },
  'aim-260': {
    id: 'aim-260',
    type: 'aam-long',
    name: 'AIM-260 JATM',
    guidance: 'active-radar',
    maxRange: 200_000,
    minRange: 2_000,
    cruiseSpeedMps: 1_250,
    terminalSpeedMps: 1_500,
    acceleration: 35,
    turnRate: 35,
    warheadWeight: 25,
    killRadius: 20,
    launchDelay: 1.5,
    lockTime: 8,
  },
  'hq-9': {
    id: 'hq-9',
    type: 'sam-long',
    name: 'HQ-9 红旗-9',
    guidance: 'semi-active',
    maxRange: 200_000,
    minRange: 5_000,
    cruiseSpeedMps: 980,
    terminalSpeedMps: 1_150,
    acceleration: 25,
    turnRate: 30,
    warheadWeight: 180,
    killRadius: 35,
    launchDelay: 3,
    lockTime: 10,
  },
  'hhq-9': {
    id: 'hhq-9',
    type: 'sam-long',
    name: 'HHQ-9 海红旗-9',
    guidance: 'semi-active',
    maxRange: 200_000,
    minRange: 5_000,
    cruiseSpeedMps: 980,
    terminalSpeedMps: 1_150,
    acceleration: 25,
    turnRate: 30,
    warheadWeight: 180,
    killRadius: 35,
    launchDelay: 3,
    lockTime: 10,
  },
  'sm-6': {
    id: 'sm-6',
    type: 'sam-long',
    name: 'SM-6 标准-6',
    guidance: 'active-radar',
    maxRange: 240_000,
    minRange: 3_000,
    cruiseSpeedMps: 920,
    terminalSpeedMps: 1_080,
    acceleration: 20,
    turnRate: 25,
    warheadWeight: 64,
    killRadius: 30,
    launchDelay: 2.5,
    lockTime: 8,
  },
  'yj-18': {
    id: 'yj-18',
    type: 'ssm',
    name: 'YJ-18 鹰击-18',
    guidance: 'active-radar',
    maxRange: 540_000,
    minRange: 10_000,
    cruiseSpeedMps: 300,
    terminalSpeedMps: 900,
    acceleration: 15,
    turnRate: 15,
    warheadWeight: 300,
    killRadius: 50,
    launchDelay: 5,
    lockTime: 15,
  },
  harpoon: {
    id: 'harpoon',
    type: 'asm',
    name: 'AGM-84 鱼叉',
    guidance: 'active-radar',
    maxRange: 220_000,
    minRange: 5_000,
    cruiseSpeedMps: 260,
    terminalSpeedMps: 310,
    acceleration: 10,
    turnRate: 10,
    warheadWeight: 221,
    killRadius: 40,
    launchDelay: 3,
    lockTime: 10,
  },
  'storm-shadow': {
    id: 'storm-shadow',
    type: 'cruise',
    name: 'Storm Shadow',
    guidance: 'gps',
    maxRange: 560_000,
    minRange: 20_000,
    cruiseSpeedMps: 270,
    terminalSpeedMps: 290,
    acceleration: 8,
    turnRate: 8,
    warheadWeight: 450,
    killRadius: 60,
    launchDelay: 4,
    lockTime: 12,
  },
  'agm-88': {
    id: 'agm-88',
    type: 'agm',
    name: 'AGM-88 HARM',
    guidance: 'passive-radar',
    maxRange: 150_000,
    minRange: 3_000,
    cruiseSpeedMps: 700,
    terminalSpeedMps: 850,
    acceleration: 25,
    turnRate: 22,
    warheadWeight: 66,
    killRadius: 25,
    launchDelay: 2,
    lockTime: 6,
  },
  'agm-154': {
    id: 'agm-154',
    type: 'bomb',
    name: 'AGM-154 JSOW',
    guidance: 'gps',
    maxRange: 130_000,
    minRange: 2_000,
    cruiseSpeedMps: 250,
    terminalSpeedMps: 280,
    acceleration: 6,
    turnRate: 12,
    warheadWeight: 225,
    killRadius: 35,
    launchDelay: 1.2,
    lockTime: 4,
  },
  rocket: {
    id: 'rocket',
    type: 'rocket',
    name: '通用火箭弹',
    guidance: 'inertial',
    maxRange: 45_000,
    minRange: 500,
    cruiseSpeedMps: 420,
    terminalSpeedMps: 520,
    acceleration: 12,
    turnRate: 8,
    warheadWeight: 30,
    killRadius: 18,
    launchDelay: 0.8,
    lockTime: 1,
  },
};

const DEFAULT_WEAPON_ID = 'aim-120d';

export function resolveWeaponSpec(weaponIds: string[] | undefined, options?: { allowDefault?: boolean }): WeaponSpec | null {
  const selectedId = weaponIds?.find((id) => WEAPON_DATABASE[id]);
  if (!selectedId && options?.allowDefault === false) return null;
  return WEAPON_DATABASE[selectedId ?? DEFAULT_WEAPON_ID];
}

export function resolveDefaultWeaponSpec(weaponIds: string[] | undefined): WeaponSpec {
  const selectedId = weaponIds?.find((id) => WEAPON_DATABASE[id]) ?? DEFAULT_WEAPON_ID;
  return WEAPON_DATABASE[selectedId];
}

export function resolveWeaponSpecForAttack(weaponIds: string[] | undefined, detail: string | undefined): WeaponSpec | null {
  const availableIds = weaponIds?.filter((id) => WEAPON_DATABASE[id]) ?? [];
  const normalizedDetail = detail?.toLowerCase() ?? '';
  const mentionedId = availableIds.find((id) => {
    const spec = WEAPON_DATABASE[id];
    return normalizedDetail.includes(id.toLowerCase()) || normalizedDetail.includes(spec.name.toLowerCase());
  });

  return resolveWeaponSpec(mentionedId ? [mentionedId] : availableIds, { allowDefault: false });
}
